version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: usage-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usage_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usage_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c log_statement=none
      -c log_min_duration_statement=1000

  api:
    image: node:20-alpine
    container_name: usage-api
    working_dir: /usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./api-usage-processor/.env
    ports:
      - "3000:3000"
    volumes:
      - ./api-usage-processor:/usr/src/app
    command: >
      sh -c "
        apk add --no-cache postgresql-client &&
        corepack enable &&
        corepack prepare pnpm@latest --activate &&
        chmod +x ./docker/entrypoint.sh &&
        ./docker/entrypoint.sh
      "

volumes:
  pgdata:
